### ISSUE TITLE
where is jdate?

### ISSUE THREAD

**Issue by jaavid** [loolooyyyy/fullcalendar-jalaali#1]
![screen shot 2018-11-06 at 8 18 53 pm](https://user-images.githubusercontent.com/1959108/48079741-3c575080-e201-11e8-8b37-17899bd92f32.png)
Uncaught ReferenceError: jdate is not defined

**Comment by loolooyyyy** [comment]
Oops. I'll fix it when I get to my laptop in an hour or two

**Comment by loolooyyyy** [comment]
Fixed. the library is now bundled with jdate, just use the latest fullcalendar.(min).js

If the problem persist, feel free to re-open this issue.
